theme: jekyll-theme-slate

title: Welcome to a dummy test webpage

description: Just trying to make a github page that is decent

markdown: kramdown
kramdown:
    math_engine: mathjax

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - test.md
  - ./pages/ducks.md
